- id: swift-proxy
  type: group
  role: [swift-proxy]
  required_for: [deploy_end]
  requires: [networking, deploy_start]
  parameters:
    strategy:
      type: parallel

- id: primary-swift-proxy
  type: group
  role: [primary-swift-proxy]
  required_for: [deploy_end]
  requires: [networking, deploy_start]
  parameters:
    strategy:
      type: one_by_one

- id: swift-storage
  type: group
  role: [swift-storage]
  required_for: [deploy_end]
  requires: [networking, deploy_start]
  parameters:
    strategy:
      type: parallel

- id: swift-proxy-deploy
  type: puppet
  groups: [primary-swift-proxy, swift-proxy]
  required_for: [connectivity_tests, deploy_end]
  requires: [netconfig, deploy_start]
  parameters:
    puppet_manifest: "puppet/manifests/proxy.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: swift-storage-deploy
  type: puppet
  groups: [swift-storage]
  required_for: [connectivity_tests, deploy_end]
  requires: [netconfig, deploy_start]
  parameters:
    puppet_manifest: "puppet/manifests/storage.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: swift-controller
  type: puppet
  groups: [primary-controller, controller]
  required_for: [connectivity_tests, deploy_end]
  requires: [openstack-controller]
  parameters:
    puppet_manifest: "puppet/manifests/controller.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600
